"""Codegen for SymPy-faithful `chem_rhs`.

Emits per-network Python source mirroring VULCAN-master's `chemdf` body
(paired `v_i = forward - reverse`, stoich-replicated multiply chains so
XLA cannot rewrite `H*H` as `exp(2*log(H))`, terminal `*M` when three-
body, asymmetric M handled per slot via `is_three_body[i]` independently
of `is_three_body[i+1]`). Source is written to
`__pycache__/chem_rhs_codegen_<hash>.py` for inspection; `build_chem_rhs`
returns a JIT'd `vmap`'d `Callable` with signature
`(y[nz, ni], M[nz], k[nr+1, nz]) -> dydt[nz, ni]`.

CLI: `python make_chem_funs.py` parses `default_config().network` and
writes the cache file. Compatibility shim for upstream `vulcan.py -n`
(no-op for VULCAN-JAX since the codegen runs at `chem_funs` import time).
"""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Any, Callable

import jax

from .network import Network


def _emit_rate_term(net: Network, slot_i: int, max_terms: int, PAD: int) -> str:
    """Emit `k[i]*y[a]*y[b]*...` (with terminal `*M` if three-body).

    Reactant slot order matches the parser's `reactants_collapsed` dict
    insertion order, which preserves first-appearance file-order. Stoich
    is expanded into literal repeated factors (`H + H` -> `y[H]*y[H]`,
    not `y[H]**2`) so XLA cannot lower the multiply chain through
    `exp(stoich*log(y))` — that lowering is what produced the ~1 ULP
    per-multiply drift the codegen is replacing.
    """
    parts = [f"k[{slot_i}]"]
    for kslot in range(max_terms):
        sp = int(net.reactant_idx[slot_i, kslot])
        st = int(net.reactant_stoich[slot_i, kslot])
        if st == 0 or sp == PAD:
            continue
        for _ in range(st):
            parts.append(f"y[{sp}]")
    if bool(net.is_three_body[slot_i]):
        parts.append("M")
    return "*".join(parts)


def emit_chem_rhs_source(net: Network) -> str:
    """Generate Python source defining `chem_rhs_per_layer_codegen` + `chem_rhs_codegen`."""
    ni, nr = net.ni, net.nr
    PAD = ni
    max_terms = net.reactant_idx.shape[1]

    lines: list[str] = [
        '"""Auto-generated by make_chem_funs.emit_chem_rhs_source -- DO NOT EDIT."""',
        "",
        "import jax",
        "import jax.numpy as jnp",
        "",
        "",
        "def chem_rhs_per_layer_codegen(y, M, k):",
        f'    """Codegen RHS, master-faithful term order. y[{ni}], M scalar, k[{nr + 1}] -> dydt[{ni}]."""',
    ]

    # Per-reaction `v_i` definitions for each forward (odd) slot. Master's
    # chemdf body collapses each (forward, reverse) pair into one `v_i =
    # forward - reverse` rate; reactions without a real reverse (photo,
    # conden, radiative, ion) keep the `- k[i+1]*...` term and rely on
    # k[i+1] == 0 at runtime to zero it out, which matches master.
    for i in range(1, nr + 1, 2):
        forward_expr = _emit_rate_term(net, i, max_terms, PAD)
        reverse_expr = _emit_rate_term(net, i + 1, max_terms, PAD)
        lines.append(f"    v_{i} = {forward_expr} - {reverse_expr}")

    # Per-species accumulators: walk forward reactions in i=1, 3, 5, ...
    # order. For each reaction, attribute its v_i to participating species
    # — products first (sign +), then reactants (sign -), each repeated by
    # stoich. This matches master line 1300's `+1*v_5 +1*v_5` for OH on
    # the product side of `O + H2O -> OH + OH` (stoich 2, two adds).
    species_terms: list[list[str]] = [[] for _ in range(ni)]
    for i in range(1, nr + 1, 2):
        for kslot in range(net.product_idx.shape[1]):
            sp = int(net.product_idx[i, kslot])
            st = int(net.product_stoich[i, kslot])
            if st == 0 or sp == PAD:
                continue
            for _ in range(st):
                species_terms[sp].append(f"+1.0*v_{i}")
        for kslot in range(max_terms):
            sp = int(net.reactant_idx[i, kslot])
            st = int(net.reactant_stoich[i, kslot])
            if st == 0 or sp == PAD:
                continue
            for _ in range(st):
                species_terms[sp].append(f"-1.0*v_{i}")

    for sp in range(ni):
        body = " ".join(species_terms[sp]) if species_terms[sp] else "0.0"
        lines.append(f"    dydt_{sp} = {body}")

    stack_args = ", ".join(f"dydt_{sp}" for sp in range(ni))
    lines.append(f"    return jnp.stack([{stack_args}], axis=-1)")
    lines.append("")
    lines.append("")
    lines.append(
        "chem_rhs_codegen = jax.vmap(chem_rhs_per_layer_codegen, in_axes=(0, 0, 1))"
    )
    lines.append("")
    return "\n".join(lines)


def chem_rhs_cache_key(net: Network) -> str:
    """SHA-256 of the network identity, truncated to 16 hex chars.

    Inputs cover every byte the codegen consumes: resolved file path, mtime,
    stoichiometry tables, reaction-type masks, ni, nr. A pure rename re-keys
    via the resolved path string (a rename leaves mtime unchanged); an in-place
    edit re-keys via mtime and the array bytes.
    """
    h = hashlib.sha256()
    p = Path(net.network_path)
    try:
        h.update(p.resolve().as_posix().encode())
        h.update(int(p.stat().st_mtime_ns).to_bytes(8, "little"))
    except (FileNotFoundError, OSError):
        h.update(net.network_path.encode())
    for arr in (
        net.reactant_idx,
        net.product_idx,
        net.reactant_stoich,
        net.product_stoich,
        net.is_three_body,
        net.is_forward,
    ):
        h.update(arr.tobytes())
    h.update(int(net.ni).to_bytes(4, "little"))
    h.update(int(net.nr).to_bytes(4, "little"))
    return h.hexdigest()[:16]


def cache_path_for(net: Network) -> Path:
    """Return the inspection-cache path for `net` (does not create it)."""
    return (
        Path(__file__).resolve().parent
        / "__pycache__"
        / f"chem_rhs_codegen_{chem_rhs_cache_key(net)}.py"
    )


_BUILD_CACHE: dict[str, Callable] = {}


def build_chem_rhs(net: Network) -> Callable:
    """Build (or load from cache) the SymPy-faithful chem_rhs for `net`.

    Returns a `jax.jit`'d callable with signature
    `(y[nz, ni], M[nz], k[nr+1, nz]) -> dydt[nz, ni]`. The XLA-compiled
    artifact is reused across processes via JAX's persistent disk cache
    (configured in `vulcan_jax_cli.py`). The Python source cache file under
    `__pycache__/` is for human inspection — `cat` it to compare against
    VULCAN-master's `chem_funs.py` reaction lambdas.
    """
    key = chem_rhs_cache_key(net)
    cached = _BUILD_CACHE.get(key)
    if cached is not None:
        return cached
    path = cache_path_for(net)
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(emit_chem_rhs_source(net))
    src = path.read_text()
    ns: dict = {}
    exec(compile(src, str(path), "exec"), ns)
    raw_fn = ns["chem_rhs_codegen"]

    def chem_rhs_codegen_barriered(y: Any, M: Any, k: Any) -> Any:
        return jax.lax.optimization_barrier(raw_fn(y, M, k))

    fn = jax.jit(chem_rhs_codegen_barriered)
    _BUILD_CACHE[key] = fn
    return fn


if __name__ == "__main__":
    import sys

    from .config import default_config
    from .network import parse_network
    from ._paths import resolve_data_path

    net = parse_network(str(resolve_data_path(default_config().network)))
    path = cache_path_for(net)
    if path.exists():
        print(f"chem_rhs codegen cache hit: {path}")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(emit_chem_rhs_source(net))
        print(f"chem_rhs codegen written: {path}")
    sys.exit(0)
