"""Measure the impact of upstream VULCAN's FastChem P/S element-slot swap.

Background (full record: ``docs/corrections_to_original_code.md`` C12). FastChem
builds its element vector in **abundance-file row order** — ``readElementAbundances``
calls ``addAtom(symbol)`` once per line and ``addAtom`` does ``elements.push_back``
with ``index = elements.size()-1``. But ``mass_action_constant.cpp`` subtracts the
per-element NASA-9 reference polynomial by *hard-coded slot index*, with
``index_P = 5`` and ``index_S = 6``. Upstream's shipped
``solar_element_abundances.dat`` lists ``... O, S, P ...``, the exact transpose, so
every S-bearing molecule's ``log_K`` is built with phosphorus's reference
polynomial and vice versa. VULCAN-JAX ships the canonical order.

This tool runs the vendored FastChem twice on the shipped W39b column — identical
binary, identical element-to-value map, **row order the only difference** — and
reports the per-species disagreement in dex. It writes nothing outside a temporary
directory and never touches the package's own FastChem tree.

Usage:
    python tools/fastchem_ps_order_impact.py
"""

from __future__ import annotations

import math
import shutil
import subprocess
import tempfile
from pathlib import Path

import numpy as np

from vulcan_jax import ini_abun

# Element order the vendored mass_action_constant.cpp hard-codes (C=0 ... e-=17).
CORRECT_ORDER = [
    "C",
    "H",
    "He",
    "N",
    "O",
    "P",
    "S",
    "Si",
    "Ti",
    "V",
    "Cl",
    "K",
    "Na",
    "Mg",
    "F",
    "Ca",
    "Fe",
    "e-",
]
# Upstream exoclime/VULCAN HEAD: S and P transposed (introduced by shami `604ca6e`).
UPSTREAM_ORDER = [
    "C",
    "H",
    "He",
    "N",
    "O",
    "S",
    "P",
    "Si",
    "Ti",
    "V",
    "Cl",
    "K",
    "Na",
    "Mg",
    "F",
    "Ca",
    "Fe",
    "e-",
]

# W39b.yaml: use_solar=false, per-element X_H, fastchem_met_scale=10 for the rest.
_W39B_X_H = {
    "C": 0.00295,
    "He": 0.0838,
    "N": 0.000708,
    "O": 0.00537,
    "S": 0.000141,
}
_W39B_MET_SCALE = 10.0
# Rocky elements are suppressed to -3.0 dex in the shipped abundance file.
_ROCKY_SUPPRESSED_DEX = -3.0

# W39b.yaml grid: nz=150 logspaced between P_b and P_t (dyne/cm^2).
_W39B_NZ = 150
_W39B_P_B = 7.6e6
_W39B_P_T = 0.1

# Mixing ratios below this are treated as absent rather than compared in log space.
_MR_FLOOR = 1e-30


def _abundances() -> dict[str, float]:
    """W39b elemental abundances as FastChem dex (12 + log10(X/H))."""
    vals = {"H": 12.0}
    for elem, x_h in _W39B_X_H.items():
        vals[elem] = 12.0 + math.log10(x_h)
    scaled = _ROCKY_SUPPRESSED_DEX + math.log10(_W39B_MET_SCALE)
    for elem in ("P", "Si", "Ti", "V", "Cl", "K", "Na", "Mg", "F", "Ca", "Fe"):
        vals[elem] = scaled
    vals["e-"] = 0.0
    return vals


def _w39b_column() -> tuple[np.ndarray, np.ndarray]:
    """The shipped W39b evening profile regridded the way VULCAN setup does.

    Returns (pressure in bar, temperature in K), both shape (_W39B_NZ,).
    """
    src = Path(ini_abun.__file__).parent / "atm" / "atm_W39b_evening_TP_Kzz.txt"
    table = np.genfromtxt(src, names=True, dtype=None, skip_header=1)
    p_tab = np.asarray(table["Pressure"], float)
    t_tab = np.asarray(table["Temp"], float)
    p_grid = np.logspace(math.log10(_W39B_P_B), math.log10(_W39B_P_T), _W39B_NZ)
    t_grid = np.interp(np.log10(p_grid[::-1]), np.log10(p_tab[::-1]), t_tab[::-1])[::-1]
    return p_grid / 1e6, t_grid


def _build_tree(root: Path) -> None:
    """Stage a minimal, self-contained FastChem working tree under `root`."""
    ini_abun._ensure_fastchem_binary()
    src = ini_abun._FC_DIR
    binary = src / "fastchem"
    if not binary.is_file():
        raise RuntimeError(
            f"FastChem binary not found at {binary}. It is compiled on first "
            "ini_mix='EQ' use; run a shipped EQ config once, or `make` in that "
            "directory, then re-run this tool."
        )
    (root / "input" / "vulcan_TP").mkdir(parents=True)
    (root / "output").mkdir()
    (root / "fastchem_src").mkdir()
    shutil.copy2(binary, root / "fastchem")
    shutil.copytree(
        src / "fastchem_src" / "chem_input", root / "fastchem_src" / "chem_input"
    )
    for name in ("nasa9_logK_SNCHOPTi.dat", "parameters_wo_ion.dat", "config.input"):
        shutil.copy2(src / "input" / name, root / "input" / name)
    shutil.move(
        str(root / "input" / "parameters_wo_ion.dat"), root / "input" / "parameters.dat"
    )


def _run(root: Path, order: list[str], vals: dict[str, float]) -> np.ndarray:
    """Write the abundance file in `order`, run FastChem, return its output table."""
    with open(root / "input" / "element_abundances_vulcan.dat", "w") as fout:
        fout.write("# generated by tools/fastchem_ps_order_impact.py\n")
        for elem in order:
            fout.write(f"{elem}\t{vals[elem]:.4f}\n")
    out = root / "output" / "vulcan_EQ.dat"
    out.unlink(missing_ok=True)
    proc = subprocess.run(
        ["./fastchem", "input/config.input"],
        cwd=root,
        capture_output=True,
        text=True,
    )
    if not out.is_file():
        raise RuntimeError(
            f"FastChem produced no output.\nstdout:\n{proc.stdout}\nstderr:\n{proc.stderr}"
        )
    return np.genfromtxt(out, names=True, dtype=None, skip_header=0)


def _dex(
    a: np.ndarray, b: np.ndarray, key: str
) -> tuple[np.ndarray, np.ndarray] | None:
    """|log10(b/a)| and the cell mask, over cells resolvable in both runs."""
    if key not in a.dtype.names:
        return None
    x = np.asarray(a[key], float)
    y = np.asarray(b[key], float)
    mask = (x > _MR_FLOOR) & (y > _MR_FLOOR)
    if not mask.any():
        return None
    return np.abs(np.log10(y[mask] / x[mask])), mask


def main() -> None:
    vals = _abundances()
    p_bar, t_k = _w39b_column()

    with tempfile.TemporaryDirectory(prefix="fc_ps_order_") as tmp:
        root = Path(tmp)
        _build_tree(root)
        with open(root / "input" / "vulcan_TP" / "vulcan_TP.dat", "w") as fout:
            fout.write("#p (bar)    T (K)\n")
            fout.write("\n".join(f"{p:.3e}\t{t:.1f}" for p, t in zip(p_bar, t_k)))
        correct = _run(root, CORRECT_ORDER, vals)
        upstream = _run(root, UPSTREAM_ORDER, vals)

    pressure = np.asarray(correct["P"], float)
    temperature = np.asarray(correct["T"], float)

    print("VULCAN-JAX (correct P/S slots) vs upstream exoclime (swapped)")
    print(f"W39b evening column, nz={_W39B_NZ}, W39b.yaml elemental abundances\n")
    header = (
        f"{'species':<8}{'max |dex|':>10}{'@P(bar)':>11}{'@T(K)':>8}"
        f"{'>0.1dex':>9}{'>0.3dex':>9}"
    )
    print(header)
    print("-" * len(header))
    # 'P' is the pressure column; genfromtxt renames atomic P to 'P_1'.
    for name in (
        "SO2",
        "H2S",
        "S",
        "S2",
        "SO",
        "COS",
        "CS",
        "H2O",
        "CO",
        "CH4",
        "CO2",
        "NH3",
        "HCN",
        "P_1",
    ):
        result = _dex(correct, upstream, name)
        if result is None:
            print(f"{name:<8}  (absent from the species set)")
            continue
        dex, mask = result
        worst = np.where(mask)[0][int(np.argmax(dex))]
        print(
            f"{name:<8}{dex.max():>10.3f}{pressure[worst]:>11.2e}"
            f"{temperature[worst]:>8.0f}{(dex > 0.1).sum():>9}{(dex > 0.3).sum():>9}"
        )

    slab = (pressure >= 1e-4) & (pressure <= 1e-2)
    print(f"\nTransit photosphere slab 1e-4..1e-2 bar ({int(slab.sum())} layers)")
    for name in ("SO2", "H2S", "S", "SO", "H2O", "CO"):
        x = np.asarray(correct[name], float)[slab]
        y = np.asarray(upstream[name], float)[slab]
        mask = (x > _MR_FLOOR) & (y > _MR_FLOOR)
        if not mask.any():
            continue
        dex = np.abs(np.log10(y[mask] / x[mask]))
        print(f"{name:<8} max {dex.max():.3f} dex   median {np.median(dex):.3f} dex")


if __name__ == "__main__":
    main()
